FROM redis:7-alpine

# Use custom redis configuration if needed
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

# For now, just using default
CMD ["redis-server"]
